import constants from 'flux-constants';

// constants returns an object in this format: { ROUTE_CHANGE: 'ROUTE_CHANGE' }
export default constants([
  'READ_ALL_CHANGEMAKERS_REQUEST',
  'READ_ALL_CHANGEMAKERS_SUCCESS',
  'READ_ALL_CHANGEMAKERS_ERROR',

  'GLOBAL_SEARCH_REQUEST',
  'GLOBAL_SEARCH_SUCCESS',
  'GLOBAL_SEARCH_ERROR',

  'SUPPORT_CHANGEMAKER',

  'GET_FEATURED_CHANGEMAKERS_REQUEST',
  'GET_FEATURED_CHANGEMAKERS_SUCCESS',
  'GET_FEATURED_CHANGEMAKERS_ERROR',

  'GET_CHANGEMAKER_BY_ID_REQUEST',
  'GET_CHANGEMAKER_BY_ID_SUCCESS',
  'GET_CHANGEMAKER_BY_ID_ERROR',

  'GET_BACKINGS_REQUEST',
  'GET_BACKINGS_SUCCESS',
  'GET_BACKINGS_ERROR',

  'GET_UPDATES_REQUEST',
  'GET_UPDATES_SUCCESS',
  'GET_UPDATES_ERROR',

  'SAVE_CHANGEMAKER_PROFILE_REQUEST',
  'SAVE_CHANGEMAKER_PROFILE_SUCCESS',
  'SAVE_CHANGEMAKER_PROFILE_ERROR',

  'UPLOAD_VIDEO_REQUEST',
  'UPLOAD_VIDEO_SUCCESS',
  'UPLOAD_VIDEO_ERROR',

  'LOGIN_SUCCESS',
	'LOGIN_ERROR',
	'LOGOUT_SUCCESS',

	'GET_USER_BY_ID_REQUEST',
	'GET_USER_BY_ID_SUCCESS',
	'GET_USER_BY_ID_ERROR',

	'SAVE_USER_PROFILE_REQUEST',
	'SAVE_USER_PROFILE_SUCCESS',
	'SAVE_USER_PROFILE_ERROR',

	'SUPPORT_CHANGEMAKER_REQUEST',
	'SUPPORT_CHANGEMAKER_SUCCESS',
	'SUPPORT_CHANGEMAKER_ERROR',

	'ADD_SUPPORT_AMOUNT',
	'SUBTRACT_SUPPORT_AMOUNT',

	'UPDATE_USER_REQUEST',
	'UPDATE_USER_SUCCESS',
	'UPDATE_USER_ERROR',

	'SUPPORT_RECURRING_CHANGEMAKER_REQUEST',
	'SUPPORT_RECURRING_CHANGEMAKER_SUCCESS',
	'SUPPORT_RECURRING_CHANGEMAKER_ERROR',

]);
