version: '2'
services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=asdfasdf
      - POSTGRES_USER=pgadmin
      - POSTGRES_DB=patron4change
  elastic:
    image: elasticsearch:2.4
    volumes:
      - "elastic-data:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
#  proxy:
#    image: nginx:
volumes:
  postgres-data:
    driver: local
  elastic-data:
    driver: local

