# TODO: tags
swagger: '2.0'
info:
  title: Changemaker API
  description: A stateless RESTful API for the core backend-communication of patron4change
  version: "1.0.0"
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /api
produces:
  - application/json
paths:
  /changemakers:
    get:
      summary: Get all Changemakers
      tags:
        - "Changemaker"
      description: |
        A list of Changemakers that can optionally be filtered.
      parameters:
        - $ref: '#/parameters/limitParam'
        - $ref: '#/parameters/offsetParam'
      responses:
        200:
          description: An array of Changemakers
          schema:
            type: array
            items:
              $ref: '#/definitions/Changemaker'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /changemakers/{changemakerId}:
    get:
      summary: Get a single Changemaker
      tags:
        - "Changemaker"
      description: |
        Returns a single Changemaker specified by id
      parameters:
        - name: changemakerId
          in: path
          required: true
          type: integer
      responses:
        200:
          description: A single Changemaker
          schema:
            $ref: '#/definitions/Changemaker'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /patrons:
    get:
      summary: Get all Patrons
      tags:
        - "Patron"
      description: |
        A list of Patrons that can optionally be filtered.
      parameters:
        - $ref: '#/parameters/limitParam'
        - $ref: '#/parameters/offsetParam'
      responses:
        200:
          description: An array of Patrons
          schema:
            type: array
            items:
              $ref: '#/definitions/Patron'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /patrons/{patronId}:
    get:
      summary: Get a single Patron
      tags:
        - "Patron"
      description: |
        Returns a single Patron specified by id
      parameters:
        - name: patronId
          in: path
          required: true
          type: integer
      responses:
        200:
          description: A single Patron
          schema:
            $ref: '#/definitions/Patron'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /backings:
    get:
      summary: Get all Backings
      tags:
        - "Backing"
      description: |
        A list of Backings that can optionally be filtered.
      parameters:
        - $ref: '#/parameters/limitParam'
        - $ref: '#/parameters/offsetParam'
        - name: changemaker_id
          in: query
          type: integer
          description: Backings to a specific Changemaker
        - name: patron_id
          in: query
          type: integer
          description: Backings by a specific Patron
      responses:
        200:
          description: An array of Backings
          schema:
            type: array
            items:
              $ref: '#/definitions/Backing'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /backings/{backingId}:
    get:
      summary: Get a single Backing
      tags:
        - "Backing"
      description: |
        One specific Backing referenced via the backingId
      parameters:
        - name: backingId
          in: path
          required: true
          type: integer
      responses:
        200:
          description: A single Backing
          schema:
            $ref: '#/definitions/Backing'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /missionupdates:
    get:
      summary: Get all Mission Updates
      tags:
        - "Update"
      description: |
        A list of Mission Updates that can optionally be filtered
      parameters:
        - $ref: '#/parameters/limitParam'
        - $ref: '#/parameters/offsetParam'
        - name: changemaker_id
          in: query
          type: integer
          description: Mission Updates by a specific Changemaker
      responses:
        200:
          description: An array of Mission Updates
          schema:
            type: array
            items:
              $ref: '#/definitions/MissionUpdate'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /missionupdates/{updateId}:
    get:
      summary: Get a single Mission Update
      tags:
        - "Update"
      description: |
        One specific Mission Update referenced via the updateId
      parameters:
        - name: updateId
          in: path
          required: true
          type: integer
      responses:
        200:
          description: A single Mission Update
          schema:
            $ref: '#/definitions/MissionUpdate'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /contentflags:
    get:
      summary: Get all Flags
      tags:
        - "Flag"
      description: |
        A list of Flags on a Changemaker or Status Update that can optionally be filtered
      parameters:
        - $ref: '#/parameters/limitParam'
        - $ref: '#/parameters/offsetParam'
        - name: user_id
          in: query
          type: integer
          description: Flags by a specific User
      responses:
        200:
          description: An array of Flags
          schema:
            type: array
            items:
              $ref: '#/definitions/Report'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /contentflags/{flagId}:
    get:
      summary: Get a single Flag
      tags:
        - "Flag"
      description: |
        One specific Report referenced via the flagId
      parameters:
        - name: flagId
          in: path
          required: true
          type: integer
      responses:
        200:
          description: A single Flag
          schema:
            $ref: '#/definitions/Report'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  UserProperties:
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier.
      first_name:
        type: string
        description: First name of the User
      last_name:
        type: string
        description: Last name of the User
      email:
        type: string
        description: Email address of the User
      isEmailValidated:
        type: boolean
        description: Email is validated
      isAnonymous:
        type: boolean
        description: Is Anonymous
      isBlocked:
        type: boolean
        description: Is blocked
      picture_location:
        type: string
        description: Image URL of the Changemaker
  Changemaker:
    allOf:
      - $ref: '#/definitions/UserProperties'
      - type: object
        properties:
          isValidated:
            type: boolean
            description: Whether the Changemaker profile has been approved by an admin
          mission:
            type: string
            description: Mission description
          tags:
            type: array
            description: Tags
            items:
              type: string
          video_location:
            type: string
            description: Video location of the Changemaker introduction
  Patron:
    allOf:
      - $ref: '#/definitions/UserProperties'
  Admin:
    allOf:
      - $ref: '#/definitions/UserProperties'
  Backing:
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier.
      changemaker_id:
        type: integer
        description: ID of the Changemaker who is backed
      patron_id:
        type: integer
        description: ID of the Patron who is backing
      type:
        type: string
        description: (enum) regular or single
      amount:
        type: integer
        description: Amount in cents
  MissionUpdate:
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier
      changemaker_id:
        type: integer
        description: ID of the Changemaker who posted this update
      title:
        type: string
        description: The title of this update
      text:
        type: string
        description: The text content of this update
  Report:
    type: object
    properties:
      reporter_id:
        type: integer
        description: User ID of then User who reported the incident
      flag_type:
        type: string
        description: "(enum) update|changemaker"
      changemaker_id:
        type: integer
        description: The changemaker who has been reported
      statusupdate_id:
        type: integer
        description: The statusupdate which has been flagged
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
parameters:
  limitParam:
    name: limit
    in: query
    type: integer
    description: 'The number of items returned'
    default: 10
  offsetParam:
    name: offset
    in: query
    type: integer
    description: The number of items skipped
    default: 0
