version: '2'
services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - "../db/create_scheme.sql:/docker-entrypoint-initdb.d/create_scheme.sql"
      - "../db/mock_data.sql:/docker-entrypoint-initdb.d/mock_data.sql"
    environment:
      - POSTGRES_PASSWORD=asdfasdf
      - POSTGRES_USER=pgadmin
      - POSTGRES_DB=patron4change
