version: '2'
services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=asdfasdf
      - POSTGRES_USER=pgadmin
      - POSTGRES_DB=patron4change
