database:
  host: localhost
  port: 5432
  database: patron4change
  user: pgadmin
  password: asdfasdf

sequelize:
	host: 'localhost'
	dialect: 'postgres'
	pool:
		max: 5
		min: 0
		idle: 10000

dataLayer: dataAccessLayer
