database:
  host: localhost
  port: 5432
  database: patron4change
  user: pgadmin
  password: asdfasdf

port: 3000

sequelize:
  host: localhost
  dialect: 'postgres'
  pool:
    max: 5
    min: 0
    idle: 10000

dataLayer: dataAccessLayer

search:
  host: localhost
  port: 3001

elasticsearch:
  host: localhost:9200

storage:
  host: p4c-storage.p-h.im
  port: 443
  bucketName: uploads
  accessKey: minio
  secretKey: jUvN0mNiZbgiphR6iEnG

queues:
  -
    name: updateSearchIndex
    config:
      batchSize: 1000
      batchDelay: 60000
